FROM microsoft/windowsservercore
ENV HAB_FEAT_INSTALL_HOOK ON
ENV OFFLINE_INSTALL ON
ADD {{rootfs}} /

EXPOSE 9631 {{exposes}}
RUN {{hab_path}} pkg install {{installed_primary_svc_ident}}
ENTRYPOINT ["{{hab_path}}", "sup", "run", "{{primary_svc_ident}}"]
